// This file will be auto-generated by `supabase gen types typescript`
// Run: pnpm db:generate
//
// For now, export a placeholder that matches the schema structure.
// Replace with generated types after connecting to Supabase.

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          handle: string;
          display_name: string | null;
          avatar_url: string | null;
          locale: "en" | "ja" | "es";
          timezone: string;
          communication_style: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["profiles"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          tier: "free" | "basic" | "pro" | "ultra";
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          ai_credits_balance: number;
          ai_credits_included: number;
          current_period_start: string | null;
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["subscriptions"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["subscriptions"]["Insert"]>;
      };
      machines: {
        Row: {
          id: string;
          user_id: string;
          fly_machine_id: string | null;
          fly_app_name: string | null;
          region: string;
          status: "provisioning" | "running" | "sleeping" | "stopped" | "error";
          cpu_cores: number;
          memory_mb: number;
          storage_gb: number;
          ip_address: string | null;
          last_active_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["machines"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["machines"]["Insert"]>;
      };
      conversations: {
        Row: {
          id: string;
          user_id: string;
          title: string | null;
          model: string;
          system_prompt: string | null;
          is_pinned: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["conversations"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["conversations"]["Insert"]>;
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          role: "user" | "assistant" | "system" | "tool";
          content: string;
          model: string | null;
          tool_calls: unknown | null;
          tool_results: unknown | null;
          token_input: number | null;
          token_output: number | null;
          cost_cents: number | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["messages"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["messages"]["Insert"]>;
      };
      memory_entries: {
        Row: {
          id: string;
          user_id: string;
          source: "screen_capture" | "meeting_transcript" | "chat" | "file" | "manual";
          content: string;
          summary: string | null;
          app_name: string | null;
          metadata: Record<string, unknown>;
          captured_at: string;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["memory_entries"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["memory_entries"]["Insert"]>;
      };
    };
    Functions: {
      search_memory: {
        Args: {
          p_user_id: string;
          p_query_embedding: number[];
          p_limit?: number;
          p_threshold?: number;
        };
        Returns: Array<{
          id: string;
          content: string;
          summary: string | null;
          source: string;
          app_name: string | null;
          captured_at: string;
          similarity: number;
        }>;
      };
      get_credits_remaining: {
        Args: { p_user_id: string };
        Returns: number;
      };
    };
  };
}
